<div id="contenedor_ver">
<?php 
    echo form_open('index.php/histo_general');
    echo form_hidden('old_id',$old_id);
    echo "<table align='center'>";
    echo "<tr>";
    echo "<td>";
    echo "<h3 align='center'>HISTORIA CLINICA GENERAL</h3>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('ID:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'id_historias_clinicas','name'=>'id_historias_clinicas', 'readonly'=>'false', 'value'=>$datos[0]->id_histo_clinicas));
        echo "</td>";
        echo "<td>";
            echo form_label('Médico:');
        echo "</td>";
        echo "<td>";
            echo form_dropdown('id_medicos', $medicos, $datosH[0]->id_medicos);
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('Fecha y paciente:');
        echo "</td>";
        echo "<td>";
            echo form_dropdown('id_reservaciones', $reservaciones, $datosH[0]->id_reservaciones);
        echo "</td>";
//        echo "<td>";
//            echo form_label('Fecha:');
//        echo "</td>";
//        echo "<td>";
//            echo form_input(array('id'=>'fecha','name'=>'fecha', 'type'=>'date', 'value'=>$datosH[0]->fecha));
//        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<h3 align='center'>AGUDEZA VISUAL</h3>";
    echo "<table border='1'>";
    echo "<tr>";
        echo "<td>";
            echo form_label(' ');
        echo "</td>";
        echo "<td>";
            echo form_label('VL');
        echo "</td>";
        echo "<td>";
            echo form_label('CC');
        echo "</td>";
        echo "<td>";
            echo form_label('VP');
        echo "</td>";
        echo "<td>";
            echo form_label('CC');
        echo "</td>";
        echo "<td>";
            echo form_label('PH');
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('O. DERECHO');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vl_od','name'=>'vl_od','readonly'=>'false', 'value'=>$datos[0]->vl_od));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc_od','name'=>'cc_od','readonly'=>'false', 'value'=>$datos[0]->cc_od));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vp_od','name'=>'vp_od','readonly'=>'false', 'value'=>$datos[0]->vp_od));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc2_od','name'=>'cc2_od','readonly'=>'false', 'value'=>$datos[0]->cc2_od));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'ph_od','name'=>'ph_od','readonly'=>'false', 'value'=>$datos[0]->ph_od));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('O. IZQUIERDO');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vl_oi','name'=>'vl_oi','readonly'=>'false', 'value'=>$datos[0]->vl_oi));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc_oi','name'=>'cc_oi','readonly'=>'false', 'value'=>$datos[0]->cc_oi));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vp_oi','name'=>'vp_oi','readonly'=>'false', 'value'=>$datos[0]->vp_oi));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc2_oi','name'=>'cc2_oi','readonly'=>'false', 'value'=>$datos[0]->cc2_oi));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'ph_oi','name'=>'ph_oi','readonly'=>'false', 'value'=>$datos[0]->ph_oi));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('DP:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'dp','name'=>'dp','readonly'=>'false', 'value'=>$datos[0]->dp));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('PPC:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'ppc','name'=>'ppc','readonly'=>'false', 'value'=>$datos[0]->ppc));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('FORIA:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'foria','name'=>'foria','readonly'=>'false', 'value'=>$datos[0]->foria));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('MOTIVO DE CONSULTA:');
            echo "<br>";
            echo form_textarea(array('id'=>'motivo_consulta','name'=>'motivo_consulta','readonly'=>'false', 'value'=>$datos[0]->motivo_consulta));
        echo "</td>";
        echo "<td>";
            echo form_label('SIGNOS Y SINTOMAS:');
            echo "<br>";
            echo form_textarea(array('id'=>'signos_sintomas','name'=>'signos_sintomas','readonly'=>'false', 'value'=>$datos[0]->signos_sintomas));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('EXAMEN EXTERNO:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'examen_externo_od','name'=>'examen_externo_od','readonly'=>'false', 'value'=>$datos[0]->examen_externo_od));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'examen_externo_oi','name'=>'examen_externo_oi','readonly'=>'false', 'value'=>$datos[0]->examen_externo_oi));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('ANTECEDENTES:');
            echo "<br>";
            echo form_textarea(array('id'=>'antecedentes','name'=>'antecedentes','readonly'=>'false', 'value'=>$datos[0]->antecedentes));
        echo "</td>";
        echo "<td>";
            echo form_label('ANTECEDENTES P:');
            echo "<br>";
            echo form_textarea(array('id'=>'antecedentes_p','name'=>'antecedentes_p','readonly'=>'false', 'value'=>$datos[0]->antecedentes_p));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('FONDO DE OJO:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'fondo_ojo_od','name'=>'fondo_ojo_od','readonly'=>'false', 'value'=>$datos[0]->fondo_ojo_od));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'fondo_ojo_oi','name'=>'fondo_ojo_oi','readonly'=>'false', 'value'=>$datos[0]->fondo_ojo_oi));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('QUERATONERIA:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'queratoneria_od','name'=>'queratoneria_od','readonly'=>'false', 'value'=>$datos[0]->queratoneria_od));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'queratoneria_oi','name'=>'queratoneria_oi','readonly'=>'false', 'value'=>$datos[0]->queratoneria_oi));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('RETINOSCOPIA:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'retinoscopia_od','name'=>'retinoscopia_od','readonly'=>'false', 'value'=>$datos[0]->retinoscopia_od));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'retinoscopia_oi','name'=>'retinoscopia_oi','readonly'=>'false', 'value'=>$datos[0]->retinoscopia_oi));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('SUBJETIVO:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'subjetivo_od','name'=>'subjetivo_od','readonly'=>'false', 'value'=>$datos[0]->subjetivo_od));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'subjetivo_oi','name'=>'subjetivo_oi','readonly'=>'false', 'value'=>$datos[0]->subjetivo_oi));
        echo "</td>";
    echo "</table>";
    echo "</td>";
    echo "</table>";
    echo form_close();
    echo "<br>";
?> 
</div>