<div id="contenedor_insertar">
<?php 
    echo form_open('index.php/histo_general/insertar_histo_general');
    echo "<table align='center'>";
    echo "<tr>";
    echo "<td>";
    echo "<h3 align='center'>REGISTRO DE HISTORIA CLINICA GENERAL</h3>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('Médico:');
        echo "</td>";
        echo "<td>";
            echo form_dropdown('id_medicos', $medicos);
        echo "</td>";
//        echo "<td>";
//            echo form_label('Paciente:');
//        echo "</td>";
//        echo "<td>";
//            echo form_dropdown('id_pacientes', $pacientes);
//        echo "</td>";
        echo "<td>";
            echo form_label('Fecha y paciente:');
        echo "</td>";
        echo "<td>";
            echo "<select id='id_reservaciones' name='id_reservaciones'>";
            echo "<option value=''>Seleccione</option>";
            foreach ($reservaciones as $i) {
                echo '<option value="'. $i->id_reservaciones .'">'. $i->fecha_paciente .'</option>';
            }   
            echo "</select>";
            echo form_error('id_reservaciones','<span class="mensaje-error-azul">','</span>');
        echo "</td>";
//    echo "<tr>";
//        echo "<td>";
//            echo form_label('Fecha:');
//        echo "</td>";
//        echo "<td>";
//            echo form_input(array('id'=>'fecha','name'=>'fecha', 'type'=>'date'));
//            echo form_error('fecha','<span class="mensaje-error-azul">','</span>');
//        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<h3 align='center'>AGUDEZA VISUAL</h3>";
    echo "<table border='1'>";
    echo "<tr>";
        echo "<td>";
            echo form_label(' ');
        echo "</td>";
        echo "<td>";
            echo form_label('VL');
        echo "</td>";
        echo "<td>";
            echo form_label('CC');
        echo "</td>";
        echo "<td>";
            echo form_label('VP');
        echo "</td>";
        echo "<td>";
            echo form_label('CC');
        echo "</td>";
        echo "<td>";
            echo form_label('PH');
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('O. DERECHO');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vl_od','name'=>'vl_od'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc_od','name'=>'cc_od'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vp_od','name'=>'vp_od'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc2_od','name'=>'cc2_od'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'ph_od','name'=>'ph_od'));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('O. IZQUIERDO');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vl_oi','name'=>'vl_oi'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc_oi','name'=>'cc_oi'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'vp_oi','name'=>'vp_oi'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'cc2_oi','name'=>'cc2_oi'));
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'ph_oi','name'=>'ph_oi'));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('DP:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'dp','name'=>'dp'));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('PPC:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'ppc','name'=>'ppc'));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('FORIA:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'foria','name'=>'foria'));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('MOTIVO DE CONSULTA:');
            echo "<br>";
            echo form_textarea(array('id'=>'motivo_consulta','name'=>'motivo_consulta'));
        echo "</td>";
        echo "<td>";
            echo form_label('SIGNOS Y SINTOMAS:');
            echo "<br>";
            echo form_textarea(array('id'=>'signos_sintomas','name'=>'signos_sintomas'));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('EXAMEN EXTERNO:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'examen_externo_od','name'=>'examen_externo_od'));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'examen_externo_oi','name'=>'examen_externo_oi'));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('ANTECEDENTES:');
            echo "<br>";
            echo form_textarea(array('id'=>'antecedentes','name'=>'antecedentes'));
        echo "</td>";
        echo "<td>";
            echo form_label('ANTECEDENTES P:');
            echo "<br>";
            echo form_textarea(array('id'=>'antecedentes_p','name'=>'antecedentes_p'));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table>";
    echo "<tr>";
        echo "<td>";
            echo form_label('FONDO DE OJO:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'fondo_ojo_od','name'=>'fondo_ojo_od'));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'fondo_ojo_oi','name'=>'fondo_ojo_oi'));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('QUERATONERIA:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'queratoneria_od','name'=>'queratoneria_od'));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'queratoneria_oi','name'=>'queratoneria_oi'));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('RETINOSCOPIA:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'retinoscopia_od','name'=>'retinoscopia_od'));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'retinoscopia_oi','name'=>'retinoscopia_oi'));
        echo "</td>";
    echo "<tr>";
        echo "<td>";
            echo form_label('SUBJETIVO:');
        echo "</td>";
        echo "<td>";
            echo form_label('OD:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'subjetivo_od','name'=>'subjetivo_od'));
        echo "</td>";
        echo "<td>";
            echo form_label('OI:');
        echo "</td>";
        echo "<td>";
            echo form_input(array('id'=>'subjetivo_oi','name'=>'subjetivo_oi'));
        echo "</td>";
    echo "</table>";
    echo "<br>";
    echo "<table align='center'>";
    echo "<tr>";
        echo "<td>";
            echo form_input(array('type'=>'image', 'src'=>'http://localhost/codeoptica/imagenes/guardar.png', 'title'=>'REGISTRAR'));
        echo "</td>";
    echo "</table>";
    echo "</td>";
    echo "</table>";
    echo form_close();
    echo "<br>";
?> 
</div>